openapi: 3.0.2
paths:
  /pull-signal:
    get:
      summary: Pull Signal
      tags: []
      parameters:
        - name: authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                type: object
                properties:
                  signalId:
                    type: number
                required:
                  - signalId
        '400':
          description: '400'
        '401':
          description: '401'
        '403':
          description: '403'
        '500':
          description: '500'
info:
  title: Pull signal Service API
  version: '1.0'
