services:
  postgres:
    image: postgres:14@sha256:2f7365d1f574dba34f6332978169afe60af9de9608fffbbfecb7d04cc5233698
    container_name: signal-hub-postgres
    environment:
      - POSTGRES_DB=signal-hub
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/signalhub-store-init.sql:/docker-entrypoint-initdb.d/01-init.sql
        # ONLY FOR PERSISTENT DATA
        # - ./postgres/data:/var/lib/postgresql/data
    # ONLY FOR PERSISTENT DATA
    # user: 501:20
    networks:
      - develop-network
    healthcheck:
      test:
        [
          "CMD",
          "psql",
          "-h",
          "localhost",
          "-p",
          "5432",
          "SELECT select 1+1 as result;",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  # ElasticMQ is a local SQS-compatible queue system, to replace AWS SQS in local development
  elasticmq:
    image: softwaremill/elasticmq-native:1.5.7@sha256:0cb5bcc04638c80af1631e8cf5da9b96b9fb6f46a4164462231065dc516c102f
    container_name: signal-hub-sqs
    ports:
      - 9324:9324
      - 9325:9325
    volumes:
      - ./elasticmq/elasticmq.local.conf:/opt/elasticmq.conf
    restart: always

  # Mockserver to simulate Interop API m2m
  mockserver:
    image: mockserver/mockserver:5.15.0@sha256:0f9ef78c94894ac3e70135d156193b25e23872575d58e2228344964273b4af6b
    ports:
      - 1080:1080
    container_name: signal-hub-mockserver
    environment:
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/webhook.json
      - MOCKSERVER_ENABLE_CORS_FOR_ALL_RESPONSES=true
      - MOCKSERVER_CORS_ALLOW_ORIGIN="*"
      - MOCKSERVER_CORS_ALLOW_METHODS="CONNECT, DELETE, GET, HEAD, OPTIONS, POST, PUT, PATCH, TRACE"
      - MOCKSERVER_CORS_ALLOW_HEADERS="Allow, Content-Encoding, Content-Length, Content-Type, ETag, Expires, Last-Modified, Location, Server, Vary, Authorization"
      - MOCKSERVER_CORS_ALLOW_CREDENTIALS="true"
      - MOCKSERVER_CORS_MAX_AGE_IN_SECONDS="300" \
    volumes:
      - "./mockserver:/config"
    networks:
      - develop-network

  zookeeper:
    image: zookeeper@sha256:c7a6a6ea6a1413ca3c13e987a4f9a1d6d2ba62b1837c3b356875842c64458b73
    networks:
      - develop-network

  kafka:
    image: quay.io/debezium/kafka:2.7@sha256:2b6aacca75457ab5476a58b9e3709368f2cd6afa37142aeef8645b2d21558c87
    ports:
      - 9092:9092
      - 29092:29092
    depends_on:
      - zookeeper
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: LISTENER_DOCKER://kafka:29092,LISTENER_HOST://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER://kafka:29092,LISTENER_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER:PLAINTEXT,LISTENER_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - develop-network
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2@sha256:8f2ff02d64b0a7a2b71b6b3b3148b85f66d00ec20ad40c30bdcd415d46d31818
    ports:
      - 8084:8080
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    networks:
      - develop-network

networks:
  develop-network:
    name: signal-hub-develop-network
    driver: bridge
