openapi: 3.0.2
paths:
  /pull-signal/{eserviceId}:
    get:
      description: Retrieve a list o signals on a specific eservice starting from signalId
      summary: Get a list of signals
      tags: []
      parameters:
        - name: eserviceId
          in: path
          required: true
          schema:
            type: string
        - name: authorization
          in: header
          required: true
          schema:
            type: string
        - name: signalId
          in: query
          schema:
            default: 0
            type: number
            minimum: 0
            nullable: true
        - name: size
          in: query
          schema:
            default: 10
            type: number
            minimum: 1
            maximum: 100
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                type: object
                properties:
                  signals:
                    type: array
                    items:
                      type: object
                      properties:
                        signalType:
                          type: string
                          enum:
                            - CREATE
                            - UPDATE
                            - DELETE
                            - SEEDUPDATE
                        objectId:
                          type: string
                        eserviceId:
                          type: string
                        signalId:
                          type: number
                        objectType:
                          type: string
                      required:
                        - signalType
                        - objectId
                        - eserviceId
                        - signalId
                        - objectType
                  lastSignalId:
                    type: number
                    nullable: true
                required:
                  - signals
        "206":
          description: "206"
          content:
            application/json:
              schema:
                type: object
                properties:
                  signals:
                    type: array
                    items:
                      type: object
                      properties:
                        signalType:
                          type: string
                          enum:
                            - CREATE
                            - UPDATE
                            - DELETE
                            - SEEDUPDATE
                        objectId:
                          type: string
                        eserviceId:
                          type: string
                        signalId:
                          type: number
                        objectType:
                          type: string
                      required:
                        - signalType
                        - objectId
                        - eserviceId
                        - signalId
                        - objectType
                  lastSignalId:
                    type: number
                    nullable: true
                required:
                  - signals
        "400":
          description: "400"
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  status:
                    type: number
                  title:
                    type: string
                  correlationId:
                    type: string
                    nullable: true
                  detail:
                    type: string
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        detail:
                          type: string
                      required:
                        - code
                        - detail
                  toString: {}
                required:
                  - type
                  - status
                  - title
                  - detail
                  - errors
                  - toString
        "401":
          description: "401"
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  status:
                    type: number
                  title:
                    type: string
                  correlationId:
                    type: string
                    nullable: true
                  detail:
                    type: string
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        detail:
                          type: string
                      required:
                        - code
                        - detail
                  toString: {}
                required:
                  - type
                  - status
                  - title
                  - detail
                  - errors
                  - toString
        "403":
          description: "403"
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  status:
                    type: number
                  title:
                    type: string
                  correlationId:
                    type: string
                    nullable: true
                  detail:
                    type: string
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        detail:
                          type: string
                      required:
                        - code
                        - detail
                  toString: {}
                required:
                  - type
                  - status
                  - title
                  - detail
                  - errors
                  - toString
        "500":
          description: "500"
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  status:
                    type: number
                  title:
                    type: string
                  correlationId:
                    type: string
                    nullable: true
                  detail:
                    type: string
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        detail:
                          type: string
                      required:
                        - code
                        - detail
                  toString: {}
                required:
                  - type
                  - status
                  - title
                  - detail
                  - errors
                  - toString
info:
  title: Pull signal Service API
  version: "1.0"
