openapi: 3.0.3
info:
  title: Pull signal Service API
  description: Exposes the API for Signal-hub pull service
  version: 1.1.0
  termsOfService: https://docs.pagopa.it/interoperabilita-1/normativa-e-approfondimenti
  license:
    name: ISC
    url: https://opensource.org/license/isc-license-txt
servers:
  - url: https://api.signalhub.interop.pagopa.it
    description: Pull signal Production URL
  - url: https://api.uat.signalhub.interop.pagopa.it
    description: Pull signal UAT URL
paths:
  /v1/pull/status:
    get:
      description: Should return OK
      summary: Health status endpoint
      operationId: getStatus
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                type: string
                enum:
                  - OK
  /v1/pull/signals/{eserviceId}:
    get:
      description: Retrieve a list o signals on a specific eservice starting from signalId
      summary: Get a list of signals
      operationId: pullSignal
      parameters:
        - schema:
            type: string
          required: true
          name: eserviceId
          in: path
        - schema:
            type: number
            nullable: true
            minimum: 0
            default: 0
          required: false
          name: signalId
          in: query
        - schema:
            type: number
            minimum: 1
            maximum: 100
            default: 10
          required: false
          name: size
          in: query
        - schema:
            type: string
          required: true
          name: authorization
          in: header
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignalPullResponse"
        "206":
          description: "206"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignalPullResponse"
        "400":
          description: "400"
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/problem"
        "401":
          description: "401"
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/problem"
        "403":
          description: "403"
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/problem"
        "500":
          description: "500"
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/problem"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: >-
        A bearer token in the format of a JWS and conformed to the
        specifications included in
        [RFC8725](https://tools.ietf.org/html/RFC8725).
  schemas:
    signalType:
      type: string
      enum:
        - CREATE
        - UPDATE
        - DELETE
        - SEEDUPDATE
    SignalPullResponse:
      type: object
      properties:
        signals:
          type: array
          items:
            type: object
            properties:
              signalType:
                $ref: "#/components/schemas/signalType"
              objectId:
                type: string
              eserviceId:
                type: string
              signalId:
                type: number
              objectType:
                type: string
            required:
              - signalType
              - objectId
              - eserviceId
              - signalId
              - objectType
        lastSignalId:
          type: number
          nullable: true
      required:
        - signals
    problem:
      type: object
      properties:
        type:
          type: string
        status:
          type: number
        title:
          type: string
        correlationId:
          type: string
          nullable: true
        detail:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
              detail:
                type: string
            required:
              - code
              - detail
      required:
        - type
        - status
        - title
        - detail
        - errors
  parameters: {}
