openapi: 3.0.2
paths:
  /push-signal:
    post:
      description: Insert a signal
      summary: Push Signal
      tags: []
      parameters:
        - name: authorization
          in: header
          required: true
          schema:
            type: string
      requestBody:
        description: Body
        content:
          application/json:
            schema:
              type: object
              properties:
                signalType:
                  type: string
                  enum:
                    - CREATE
                    - UPDATE
                    - DELETE
                    - SEEDUPDATE
                objectId:
                  type: string
                eserviceId:
                  type: string
                signalId:
                  type: number
                objectType:
                  type: string
              required:
                - signalType
                - objectId
                - eserviceId
                - signalId
                - objectType
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                type: object
                properties:
                  signalId:
                    type: number
                required:
                  - signalId
        '400':
          description: '400'
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  status:
                    type: number
                  title:
                    type: string
                  correlationId:
                    type: string
                    nullable: true
                  detail:
                    type: string
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        detail:
                          type: string
                      required:
                        - code
                        - detail
                  toString: {}
                required:
                  - type
                  - status
                  - title
                  - detail
                  - errors
                  - toString
        '401':
          description: '401'
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  status:
                    type: number
                  title:
                    type: string
                  correlationId:
                    type: string
                    nullable: true
                  detail:
                    type: string
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        detail:
                          type: string
                      required:
                        - code
                        - detail
                  toString: {}
                required:
                  - type
                  - status
                  - title
                  - detail
                  - errors
                  - toString
        '403':
          description: '403'
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  status:
                    type: number
                  title:
                    type: string
                  correlationId:
                    type: string
                    nullable: true
                  detail:
                    type: string
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        detail:
                          type: string
                      required:
                        - code
                        - detail
                  toString: {}
                required:
                  - type
                  - status
                  - title
                  - detail
                  - errors
                  - toString
        '500':
          description: '500'
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  status:
                    type: number
                  title:
                    type: string
                  correlationId:
                    type: string
                    nullable: true
                  detail:
                    type: string
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        detail:
                          type: string
                      required:
                        - code
                        - detail
                  toString: {}
                required:
                  - type
                  - status
                  - title
                  - detail
                  - errors
                  - toString
info:
  title: Push signal Service API
  version: '1.0'
