openapi: 3.0.2
paths:
  /status:
    get:
      description: Should return OK
      summary: Health status endpoint
      tags: []
      parameters: []
      operationId: getStatus
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                type: string
                enum:
                  - OK
  /signals:
    post:
      description: Insert a signal
      summary: Push Signal
      tags: []
      parameters:
        - name: authorization
          in: header
          required: true
          schema:
            type: string
      operationId: pushSignal
      requestBody:
        description: Body
        content:
          application/json:
            schema:
              type: object
              properties:
                signalType:
                  type: string
                  enum:
                    - CREATE
                    - UPDATE
                    - DELETE
                    - SEEDUPDATE
                objectId:
                  type: string
                eserviceId:
                  type: string
                signalId:
                  type: number
                objectType:
                  type: string
              required:
                - signalType
                - objectId
                - eserviceId
                - signalId
                - objectType
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                type: object
                properties:
                  signalId:
                    type: number
                required:
                  - signalId
        '400':
          description: '400'
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  status:
                    type: number
                  title:
                    type: string
                  correlationId:
                    type: string
                    nullable: true
                  detail:
                    type: string
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        detail:
                          type: string
                      required:
                        - code
                        - detail
                  toString: {}
                required:
                  - type
                  - status
                  - title
                  - detail
                  - errors
                  - toString
        '401':
          description: '401'
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  status:
                    type: number
                  title:
                    type: string
                  correlationId:
                    type: string
                    nullable: true
                  detail:
                    type: string
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        detail:
                          type: string
                      required:
                        - code
                        - detail
                  toString: {}
                required:
                  - type
                  - status
                  - title
                  - detail
                  - errors
                  - toString
        '403':
          description: '403'
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  status:
                    type: number
                  title:
                    type: string
                  correlationId:
                    type: string
                    nullable: true
                  detail:
                    type: string
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        detail:
                          type: string
                      required:
                        - code
                        - detail
                  toString: {}
                required:
                  - type
                  - status
                  - title
                  - detail
                  - errors
                  - toString
        '500':
          description: '500'
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  status:
                    type: number
                  title:
                    type: string
                  correlationId:
                    type: string
                    nullable: true
                  detail:
                    type: string
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        detail:
                          type: string
                      required:
                        - code
                        - detail
                  toString: {}
                required:
                  - type
                  - status
                  - title
                  - detail
                  - errors
                  - toString
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: >-
        A bearer token in the format of a JWS and conformed to the
        specifications included in
        [RFC8725](https://tools.ietf.org/html/RFC8725).
security:
  - bearerAuth: []
servers:
  - url: /signals
    description: Push signal data
info:
  title: Push signal Service API
  version: 1.2.0
  license:
    name: ISC
    url: https://opensource.org/license/isc-license-txt
  contact:
    name: PagoPA support
    url: https://github.com/pagopa/interop-signalhub-core/issues
    email: Interop-sprint@pagopa.it
  termsOfService: https://docs.pagopa.it/interoperabilita-1/normativa-e-approfondimenti
