name: "Build & Push"

on:
  push:
    branches:
      - "main"
    tags:
      - "*"
    paths:
      - "packages/**"
      - "!packages/*/scripts/**"
      - ".github/workflows/build-push.yaml"

jobs:
  find_dockerfiles:
  name: Find Dockerfiles
  runs-on: ubuntu-latest
  outputs:
    packages: ${{ steps.set_packages_output.outputs.packages }}
  steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
    - name: Find packages
      id: set_packages_output
      run: |
        PACKAGES=$(find packages -type f -path "*/Dockerfile" | awk -F'/' '{print $2}' | jq -R -s -c 'split("\n")[:-1]')
        echo "packages=$PACKAGES" >> $GITHUB_OUTPUT

  build_push_image:
    name: ${{ matrix.image_name }}
    runs-on: ubuntu-latest
    environment: ecr
    needs: [find_dockerfiles]
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.find_dockerfiles.outputs.packages) }}
    permissions:
      contents: read
      id-token: write
    env:
      DOCKER_BUILD_SUMMARY: "false"

    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
          role-session-name: signalhub-core-build-push-${{ github.run_number }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2

      - name: (latest) Docker metadata
        id: meta_latest
        if: ${{ github.ref_type == 'branch' }}
        uses: docker/metadata-action@f7b4ed12385588c3f9bc252f0a2b520d83b52d48
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/signalhub-be-${{ matrix.image_name }}
          flavor: |
            latest=false
            prefix=
            suffix=
          tags: |
            type=raw,value=1.x-latest

      - name: (tag) Docker metadata
        id: meta_tag
        if: ${{ github.ref_type == 'tag' }}
        uses: docker/metadata-action@f7b4ed12385588c3f9bc252f0a2b520d83b52d48
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/signalhub-be-${{ matrix.image_name }}
          flavor: |
            latest=false
            prefix=
            suffix=
          tags: |
            type=ref,event=tag

      - name: Build and push Docker image
        id: build_push
        uses: docker/build-push-action@84354d3b32f6fcad27a04f6b82436bfb39425d16
        with:
          context: .
          file: packages/${{ matrix.package }}/Dockerfile
          push: true
          tags: ${{ github.ref_type == 'branch' && steps.meta_latest.outputs.tags || steps.meta_tag.outputs.tags }}
          labels: ${{ github.ref_type == 'branch' && steps.meta_latest.outputs.labels || steps.meta_tag.outputs.labels }}
